dist: xenial
services:
  - postgresql
addons:
  postgresql: '9.4'
  chrome: stable
before_script:
  - psql -U postgres -c "create user decide1 password 'complexpassword'"
  - psql -U postgres -c "create database decidedb1 owner decide1"
  - psql -U postgres -c "ALTER USER decide1 CREATEDB"
language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install selenium
script:
  - cd decide
  - cp local_settings_travis.py local_settings.py
  - coverage run --branch --source=. ./manage.py test store --keepdb

